build:
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        # Add the respective Scrutinizer analysis for your language like
        override: [php-scrutinizer-run]

filter:
  # Everything in a root level "tests" directory will be excluded
  excluded_paths: [tests/*]
  # Everything in a root level "vendor" directory will be excluded from analysis
  # but treated as a dependency
  dependency_paths: [vendor/]

checks:
  php:
    remove_extra_empty_lines: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true
    fix_use_statements:
      remove_unused: true
      preserve_multiple: false
      preserve_blanklines: true
      order_alphabetically: true
    fix_php_opening_tag: true
    fix_linefeed: true
    fix_line_ending: true
    fix_identation_4spaces: true
    fix_doc_comments: true

tools:
  external_code_coverage:
    timeout: 600    # Timeout in seconds.
    runs: 3
